### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by cloppy** [mongodb/js-bson#123]
When trying to install `mongoose`, it always produces a builderror.log file when trying to install bson.

The content is the following:

```
child_process: customFds option is deprecated, use stdio instead.
gyp: binding.gyp not found (cwd: /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Johannes/Documents/Development/holmes/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

So where is the binding.gyp file? It's also not in the repo (as far as I can see).

**Comment by cloppy** [comment]
Seems like `binding.gyp` was still available in 0.2.21, why isn't include in 0.3.x?

**Comment by christkv** [comment]
the c++ code is bson-ext which an optional dependency

**Comment by christkv** [comment]
removed npm install node-gyp line from module
