### ISSUE TITLE
calculateObjectSize calculates wrong size

### ISSUE THREAD

**Issue by vird** [mongodb/js-bson#142]
size = BSON.calculateObjectSize(data, false)
console.log("size="+size)
buffer = new Buffer(size)
BSON.serializeWithBufferAndIndex(data, false, buffer, false, false)

    size=41094593
    RangeError: attempt to write outside buffer bounds
      at Buffer.write (buffer.js:419:11)
      at serializeNumber (/root/node_modules/bson/lib/bson/parser/serializer.js:106:39)
      at serializeInto (/root/node_modules/bson/lib/bson/parser/serializer.js:609:17)
      at serializeObject (/root/node_modules/bson/lib/bson/parser/serializer.js:276:18)
      at serializeInto (/root/node_modules/bson/lib/bson/parser/serializer.js:548:17)
      at serializeObject (/root/node_modules/bson/lib/bson/parser/serializer.js:276:18)
      at serializeInto (/root/node_modules/bson/lib/bson/parser/serializer.js:624:17)
      at serializeObject (/root/node_modules/bson/lib/bson/parser/serializer.js:276:18)
      at serializeInto (/root/node_modules/bson/lib/bson/parser/serializer.js:624:17)
      at [object Object].BSON.serializeWithBufferAndIndex (/root/node_modules/bson/lib/bson/bson.js:68:27)

I'll try to found some small amount of data for reproduce.

**Comment by vird** [comment]
var i, obj;
    
    obj = [];
    
    for (i = 0; i < 1460000; i++) {
      obj.push(i);
    }
    
    serialize(obj);

**Comment by christkv** [comment]
it does not support serializing arrays like that. it expects an object.

**Comment by vird** [comment]
https://github.com/mongodb/js-bson/pull/143
problem was in serializeWithBufferAndIndex

**Comment by vird** [comment]
Nope with less size all works ok.

**Comment by vird** [comment]
You mean that bson-ext don't support arrays

**Comment by christkv** [comment]
answered on pull request.
