### ISSUE TITLE
Cannot compile c++ extension in ubuntu 14.04

### ISSUE THREAD

**Issue by Lughino** [mongodb/js-bson#154]
Hi,
i tried to compile this library with ubuntu but errors occurred.
This is the output:
```bash
make: Entering directory `/bioshopdemo/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../ext/bson.cc:24:0:
/home/lughino/.node-gyp/4.2.2/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/lughino/.node-gyp/4.2.2/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/lughino/.node-gyp/4.2.2/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/lughino/.node-gyp/4.2.2/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../ext/bson.cc: In static member function ‘static void BSON::BSONDeserialize(const v8::FunctionCallbackInfo<v8::Value>&)’:
../ext/bson.cc:825:44: warning: ‘ssize_t node::DecodeBytes(v8::Local<v8::Value>, node::encoding)’ is deprecated (declared at /home/lughino/.node-gyp/4.2.2/src/node.h:317): Use DecodeBytes(isolate, ...) [-Wdeprecated-declarations]
   ssize_t len = DecodeBytes(args[0], BINARY);
                                            ^
../ext/bson.cc:833:41: warning: ‘ssize_t node::DecodeWrite(char*, size_t, v8::Local<v8::Value>, node::encoding)’ is deprecated (declared at /home/lughino/.node-gyp/4.2.2/src/node.h:330): Use DecodeWrite(isolate, ...) [-Wdeprecated-declarations]
   DecodeWrite(data, len, args[0], BINARY);
                                         ^
../ext/bson.cc: In static member function ‘static void BSON::BSONSerialize(const v8::FunctionCallbackInfo<v8::Value>&)’:
../ext/bson.cc:928:73: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node::encoding)’ is deprecated (declared at /home/lughino/.node-gyp/4.2.2/src/node.h:298): Use Encode(isolate, ...) [-Wdeprecated-declarations]
   Local<Value> bin_value = Encode(serialized_object, object_size, BINARY)->ToString();
                                                                         ^
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:673:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make: *** [Release/obj.target/bson/ext/bson.o] Error 1
make: Leaving directory `/bioshopdemo/node_modules/mongodb/node_modules/bson/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /bioshopdemo/node_modules/mongodb/node_modules/bson
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok 
```

I installed `node-gyp` on global and `gcc make build-essential libkrb5-dev` but i get always this error.
Can you resolve this issue?
I need to install in production environment.

Thanks

**Comment by smartmouse** [comment]
Can you please check your gcc version on the machine?

**Comment by christkv** [comment]
why are you attempting to install this library ?

**Comment by smartmouse** [comment]
I remember that mongodb will default to the pure java script implementation if bson is not working.

**Comment by christkv** [comment]
2.0.x drive does not use the module anymore as the js one is only 5% slower after it was painstakingly optimized :)

**Comment by christkv** [comment]
1.4 supports 0.10.x if you want 0.12.x or higher you need to use 2.x. Blame V8 on the continuous changes in the c++ api's.

**Comment by smartmouse** [comment]
when you do npm install mongodb -- you can specify a particular version, npm install mongodb@1.4.38,  or in your application package.json file. you can specify an older version of mongodb, then it give you an older version of bson that is compatible to node 0.10.x

**Comment by kusold** [comment]
@christkv Is it possible to pull in `bson-ext` for `~0.2`? I may not understand the relationship between the two projects, but `bson-ext V0.1.13` builds successfully for me while I can't get `0.2.x` to compile at all.

Unfortunately we are tied to `mongoose 3.x`, which relies on `"mongodb": "1.4.38"` which relies on `"bson": "~0.2"`

Fedora 22
Node 4.2.3

❯ python --version
Python 2.7.10

❯ gcc --version
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

❯ g++ --version
g++ (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

**Comment by christkv** [comment]
Node 4.x is not supported for 1.4.x for the bson-ext. I do not plan to upgrade bson-ext to confirm with node 4.x as the 2.x.x series of the driver no longer uses the extension.

A failed bson-ext install does not stop the driver from installing it just means the driver defaults to the pure JS parser ignoring the failed boon-ext module.

**Comment by boutell** [comment]
Since the fallback to JS does no harm, is there a way to suppress the warning on every launch without hacking up the mongodb 1.x driver myself?

Console output from every single cron job in the world is a nontrivial problem. Thanks!

**Comment by t1bb4r** [comment]
I've researched the "error" a lot and the log caused a lot of confusion in the community. If you google the error you see hundreds of developers are/were confused by the message "{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }". Can't blame some one for thinking that is an error at first glance... They are eventually told by an experienced developer "don't worry it is just a warning' or "upgrade mongoose".

My problem is Logentries and many other log management software detects the string "Error" and emails me that there is something wrong. Sure the regex could be upgraded, but myself and I think many other developers stuck on mongoose 3.8 would really appreciate it if you could either remove the log or change it to a warning. The actual problem for me is the `console.dir(err)` code which produces the "Error" string, because it the object being logged is an instance of the Error class.
