### ISSUE TITLE
windows build errors for bson@0.1.9

### ISSUE THREAD

**Issue by b-admike** [mongodb/js-bson#183]
Hi,
I'm hitting compilation issue on a Windows 7 laptop with node v0.12.9 and npm v3.9.2 trying to install bson@0.1.9. This is a little snippet from the install output:

``` console
..\ext\bson.cc(605): error C2039: 'New': is not a member of 'v8::String' [C:\Us
ers\nodebot\AppData\Roaming\npm\node_modules\bson\build\bson.vcxproj]
  C:\Users\nodebot\.node-gyp\0.12.9\deps\v8\include\v8.h(1599): note: see decla
  ration of 'v8::String'
..\ext\bson.cc(605): error C2664: 'v8::Handle<v8::Value> BSON::New(const int)':
 cannot convert argument 1 from 'const char [4]' to 'const int' [C:\Users\nodeb
ot\AppData\Roaming\npm\node_modules\bson\build\bson.vcxproj]
  ..\ext\bson.cc(605): note: There is no context in which this conversion is po
  ssible
..\ext\bson.cc(605): error C2660: 'v8::PersistentBase<T>::New': function does n
ot take 1 arguments [C:\Users\nodebot\AppData\Roaming\npm\node_modules\bson\bui
ld\bson.vcxproj]
          with
          [
              T=v8::String
          ]
```

I have MS Visual Studio 2015 installed and `msvs_version` for npm config set to `2015`. Here are the contents of builderror.log:

```
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nodebot\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\nodebot\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nodebot\AppData\Roaming\npm\node_modules\bson
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by christkv** [comment]
use latest bson instead as it does not pull any native modules
