### ISSUE TITLE
facing problem in starting the Node.js Compiler.

### ISSUE THREAD

**Issue by rishabhbahukhandi** [mongodb/js-bson#186]
I am New in Node.js and mongo db.

i have Installed it on Server.
But when i am running my node Server.js file..
i have Encouter with this problem 

[root@ip-172-31-25-13 ~]# node server.js
[Error: /root/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build/Release/bson.node: invalid ELF header]
js-bson: Failed to load c++ bson extension, using pure JS version
module.js:338
    throw err;
          ^
Error: Cannot find module './app/models/Nerd'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/server.js:36:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

pls help in this..

**Comment by rishabhbahukhandi** [comment]
I am New in Node.js and mongo db.


i have Installed it on Server.
But when i am running my node Server.js file..
i have Encouter with this problem 






[root@ip-172-31-25-13 ~]# node server.js
[Error: /root/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build/Release/bson.node: invalid ELF header]
js-bson: Failed to load c++ bson extension, using pure JS version
module.js:338
    throw err;
          ^
Error: Cannot find module './app/models/Nerd'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/server.js:36:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3



pls help in this..

**Comment by christkv** [comment]
I would suggest starting with a decent course. There is a free MEAN course online.

https://www.edx.org/course/introduction-mongodb-using-mean-stack-mongodbx-m101x-0
