### ISSUE TITLE
Error: Cannot find module './int_32'

### ISSUE THREAD

**Issue by AdamBCo** [mongodb/js-bson#191]
I keep getting the following error when trying to deploy my app.

    Error: Cannot find module './int_32'
      at Function.Module._resolveFilename (module.js:440:15)
      at Function.Module._load (module.js:388:25)
      at Module.require (module.js:468:17)
      at require (internal/module.js:20:19)
      at /app/node_modules/bson/lib/bson/index.js:21:17
      at Array.forEach (native)
      at Object.<anonymous> (/app/node_modules/bson/lib/bson/index.js:20:15)
      at Module._compile (module.js:541:32)
      at Object.Module._extensions..js (module.js:550:10)
      at Module.load (module.js:458:32)

Any help debugging this issue would be greatly appreciated.

Thanks

**Comment by Frosty-Z** [comment]
Looking at `bson/lib/bson/index.js` file, it tries to load an `int_32.js` file in same directory which is not present.

**Comment by christkv** [comment]
closing as it was probably a npm cache issue
