### ISSUE TITLE
Some recursion issue in calculate_size.js which hits maximum call stack limit.

### ISSUE THREAD

**Issue by ashish314** [mongodb/js-bson#210]
Below is error i get when i am trying to insert data in mongo db with native mongo client.

```
RangeError: Maximum call stack size exceeded
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:74:33)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
    at calculateObjectSize (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:38:22)
    at calculateElement (/Users/ashish/greenClouds/dashboard/node_modules/bson/lib/bson/parser/calculate_size.js:123:77)
```

**Comment by Loksly** [comment]
is it possible that the data you are trying to insert is recursive?
I mean that one of it's attributes or children it's bind to itself.

This kind of error may happen with an object like this:
```js
    var doc = {'data': 1}
    doc.attr = doc;
    
    var size = bson.calculateObjectSize(doc);
```

Here you can see this same example failing:
https://jsfiddle.net/byt2zm5q/

**Comment by ashish314** [comment]
Yes, i got this error when i was trying to insert some data in mongo db with native mongo client for node js.
My data mostly will be like {'data': 1}, how can i solve this.?

**Comment by mbroadst** [comment]
@ashish314 I think what @Loksly was suggesting was not that there was an issue with a document that looks like `{ data: 1 }`, but rather a document that looks like: `{ data: 1, attr: [ Cyclic reference back to this doc ] }`. Can you please provide a minimal test case to reproduce your issue?

**Comment by ashish314** [comment]
@mbroadst @Loksly My bad there, in my case the object i was trying to insert in db was something like below,

[ CommandResult {
    result: { ok: 1, nModified: 1, n: 1 },
    connection:
     Connection {
       domain: null,
       _events: [Object],
       _eventsCount: 4,
       _maxListeners: undefined,
       options: [Object],
       id: 0,
       logger: [Object],
       bson: BSON {},
       tag: undefined,
       messageHandler: [Function],
       maxBsonMessageSize: 67108864,
       port: 27017,
       host: 'localhost',
       family: 4,
       keepAlive: true,
       keepAliveInitialDelay: 300000,
       noDelay: true,
       connectionTimeout: 30000,
       socketTimeout: 360000,
       destroyed: false,
       domainSocket: false,
       singleBufferSerializtion: true,
       serializationFunction: 'toBinUnified',
       ca: null,
       crl: null,
       cert: null,
       key: null,
       passphrase: null,
       ssl: false,
       rejectUnauthorized: false,
       checkServerIdentity: true,
       responseOptions: [Object],
       flushing: false,
       queue: [],
       connection: [Object],
       writeStream: null,
       hashedName: '29bafad3b32b11dc7ce934204952515ea5984b3c',
       workItems: [],
       buffer: null,
       sizeOfMessage: 0,
       bytesRead: 0,
       stubBuffer: null },
    message:
     Response {
       parsed: true,
       index: 71,
       raw: <Buffer 47 00 00 00 2f 5e 01 00 4e 00 00 00 01 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 23 00 00 00 10 6f 6b 00 01 00 00 00 10 6e ... >,
       data: <Buffer 47 00 00 00 2f 5e 01 00 4e 00 00 00 01 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 23 00 00 00 10 6f 6b 00 01 00 00 00 10 6e ... >,
       bson: BSON {},
       opts: [Object],
       length: 71,
       requestId: 89647,
       responseTo: 78,
       responseFlags: 8,
       cursorId: [Object],
       startingFrom: 0,
       numberReturned: 1,
       documents: [Object],
       cursorNotFound: false,
       queryFailure: false,
       shardConfigStale: false,
       awaitCapable: true,
       promoteLongs: true,
       promoteValues: true,
       promoteBuffers: false,
       hashedName: '29bafad3b32b11dc7ce934204952515ea5984b3c' } } ] 

Which is insanely wrong, i fixed it and now everything works like a charm.
Thanks everyone for helping and i also understand now the cyclic reference of a object which may cause that error.

**Comment by Loksly** [comment]
Good to know that now everything is ok.
There was another way to check if there was a cycle, try to serialize to JSON using this:

```js
JSON.stringify(obj)
```

Then if it is you'll see in console something like the next error message:

```txt
VM170:65 Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
```

**Comment by ashish314** [comment]
roger that.

**Comment by mbroadst** [comment]
@ashish314 👍
