### ISSUE TITLE
Failed to load c++ bson extension, using pure JS version :/

### ISSUE THREAD

**Issue by itsacorn** [mongodb/js-bson#229]
Hello everyone, i am getting this annoying warning that causes PM2 to restart the script: 
```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/Wrapper.js:48:31)
    at Module.require (module.js:568:17)
    at Module.proto.require (/usr/lib/node_modules/common-node/lib/run.js:33:38)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/server/web/main/node_modules/mongo-sync/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Restart successful. Time: 15 Nov 2017 20:44:14
```

When i try to build the binary with `node-gyp build`, i get this error: 
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/server/web/main/node_modules/mongo-sync/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
In file included from ../../nan/nan.h:82:0,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_new.h: In function ‘v8::Local<T> NanIntern::To(v8::Handle<v8::Integer>) [with T
../../nan/nan_new.h:34:64: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is depr
 To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
                                                                ^
In file included from ../ext/bson.cc:14:0:
/root/.node-gyp/8.5.0/include/node/v8.h:9614:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^~~~~
In file included from ../../nan/nan.h:82:0,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_new.h: In function ‘v8::Local<T> NanIntern::To(v8::Handle<v8::Integer>) [with T
../../nan/nan_new.h:39:65: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is de
 To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
                                                                 ^
In file included from ../ext/bson.cc:14:0:
/root/.node-gyp/8.5.0/include/node/v8.h:9608:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa
../../nan/nan_implementation_12_inl.h:49:38: warning: ‘static v8::Local<v8::Value> v8::Boolea
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:4749:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa
../../nan/nan_implementation_12_inl.h:166:69: warning: ‘static v8::Local<v8::Script> v8::Scri)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1380:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBaiptOrigin&)’:
../../nan/nan_implementation_12_inl.h:173:69: warning: ‘static v8::Local<v8::Script> v8::Scri)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1380:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa
../../nan/nan_implementation_12_inl.h:206:42: warning: ‘static v8::Local<v8::String> v8::StriUse maybe version [-Wdeprecated-declarations]
         v8::String::kNormalString, length);
                                          ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:2626:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa’:
../../nan/nan_implementation_12_inl.h:217:66: warning: ‘static v8::Local<v8::String> v8::Striion [-Wdeprecated-declarations]
   return v8::String::NewExternal(v8::Isolate::GetCurrent(), value);
                                                                  ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:2664:38: note: declared here
                        Local<String> NewExternal(
                                      ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa’:
../../nan/nan_implementation_12_inl.h:237:30: warning: ‘static v8::Local<v8::UnboundScript> vCompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^~~~~~~~~~~~~~
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1360:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h:237:76: warning: ‘static v8::Local<v8::UnboundScript> vCompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1360:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBa const v8::ScriptOrigin&)’:
../../nan/nan_implementation_12_inl.h:244:30: warning: ‘static v8::Local<v8::UnboundScript> vCompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^~~~~~~~~~~~~~
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1360:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:82,
                 from ../ext/bson.h:17,
                 from ../ext/bson.cc:36:
../../nan/nan_implementation_12_inl.h:244:76: warning: ‘static v8::Local<v8::UnboundScript> vCompileOptions)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1360:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../../nan/nan.h: At global scope:
../../nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLoca
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘bool NanIdleNotification(int)’:
../../nan/nan.h:289:71: warning: ‘bool v8::Isolate::IdleNotification(int)’ is deprecated: use
     return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                                                       ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:7335:22: note: declared here
                 bool IdleNotification(int idle_time_in_ms));
                      ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../../nan/nan.h: At global scope:
../../nan/nan.h:473:20: error: variable or field ‘NanAddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:473:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:474:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:479:20: error: variable or field ‘NanRemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:479:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:484:20: error: variable or field ‘NanAddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:484:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:485:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:490:20: error: variable or field ‘NanRemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:490:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^~
../../nan/nan.h:569:15: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
               ^~~~~~~~~~~~~~~~
../../nan/nan.h:569:31: error: expected ‘,’ or ‘...’ before ‘<’ token
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
                               ^
../../nan/nan.h: In function ‘void _NanWeakCallbackDispatcher(int)’:
../../nan/nan.h:570:42: error: ‘data’ was not declared in this scope
       _NanWeakCallbackInfo<T, P> *info = data.GetParameter();
                                          ^~~~
../../nan/nan.h: At global scope:
../../nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^~~~~~~
../../nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^~~~~~~~
../../nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
../../nan/nan.h:672:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../ext/bson.cc:24:0:
/root/.node-gyp/8.5.0/include/node/node_buffer.h:67:40: note:   initializing argument 2 of ‘v
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^~~
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../../nan/nan.h:672:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent()
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:676:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent()
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^~~~
../../nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>, c
../../nan/nan.h:710:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1380:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../ext/bson.h:17:0,
                 from ../ext/bson.cc:36:
../../nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>)’:
../../nan/nan.h:717:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:1380:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc: In member function ‘v8::Handle<v8::Value> BSONDeserializer::DeserializeDocume
../ext/bson.cc:457:37: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8precated-declarations]
   returnObject->ForceSet(name, value);
                                     ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3056:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:466:61: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
   return NanNew(bson->dbrefConstructor)->NewInstance(3, argv);
                                                             ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc: In member function ‘v8::Handle<v8::Value> BSONDeserializer::DeserializeValue(
../ext/bson.cc:523:66: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->timestampConstructor)->NewInstance(2, argv);
                                                                  ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:542:61: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->codeConstructor)->NewInstance(2, argv);
                                                             ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:551:61: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->codeConstructor)->NewInstance(2, argv);
                                                             ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:557:65: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->objectIDConstructor)->NewInstance(1, argv);
                                                                 ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:572:63: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->binaryConstructor)->NewInstance(2, argv);
                                                               ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:595:61: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->longConstructor)->NewInstance(2, argv);
                                                             ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:611:63: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Loc
    return NanNew(bson->symbolConstructor)->NewInstance(1, argv);
                                                               ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3788:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:615:55: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is
   return NanNew(bson->minKeyConstructor)->NewInstance();
                                                       ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3792:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc:618:55: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is
   return NanNew(bson->maxKeyConstructor)->NewInstance();
                                                       ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3792:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc: In static member function ‘static void BSON::Initialize(v8::Handle<v8::Object
../ext/bson.cc:681:59: warning: ‘bool v8::Object::ForceSet(v8::Local<v8::Value>, v8::Local<v8precated-declarations]
  target->ForceSet(NanNew<String>("BSON"), t->GetFunction());
                                                           ^
In file included from /root/.node-gyp/8.5.0/include/node/v8.h:26:0,
                 from ../ext/bson.cc:14:
/root/.node-gyp/8.5.0/include/node/v8.h:3056:22: note: declared here
                 bool ForceSet(Local<Value> key, Local<Value> value,
                      ^
/root/.node-gyp/8.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECA
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../ext/bson.cc: In static member function ‘static void BSON::BSONDeserialize(const v8::Functi
../ext/bson.cc:825:44: warning: ‘ssize_t node::DecodeBytes(v8::Local<v8::Value>, node::encodi
   ssize_t len = DecodeBytes(args[0], BINARY);
                                            ^
In file included from ../ext/bson.cc:22:0:
/root/.node-gyp/8.5.0/include/node/node.h:374:32: note: declared here
                 inline ssize_t DecodeBytes(
                                ^
/root/.node-gyp/8.5.0/include/node/node.h:87:42: note: in definition of macro ‘NODE_DEPRECATE
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../ext/bson.cc:833:41: warning: ‘ssize_t node::DecodeWrite(char*, size_t, v8::Local<v8::Value
   DecodeWrite(data, len, args[0], BINARY);
                                         ^
In file included from ../ext/bson.cc:22:0:
/root/.node-gyp/8.5.0/include/node/node.h:387:32: note: declared here
                 inline ssize_t DecodeWrite(char* buf,
                                ^
/root/.node-gyp/8.5.0/include/node/node.h:87:42: note: in definition of macro ‘NODE_DEPRECATE
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../ext/bson.cc: In static member function ‘static void BSON::BSONSerialize(const v8::Function
../ext/bson.cc:928:73: warning: ‘v8::Local<v8::Value> node::Encode(const void*, size_t, node:
   Local<Value> bin_value = Encode(serialized_object, object_size, BINARY)->ToString();
                                                                         ^
In file included from ../ext/bson.cc:22:0:
/root/.node-gyp/8.5.0/include/node/node.h:355:45: note: declared here
                 inline v8::Local<v8::Value> Encode(
                                             ^
/root/.node-gyp/8.5.0/include/node/node.h:87:42: note: in definition of macro ‘NODE_DEPRECATE
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
bson.target.mk:93: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: *** [Release/obj.target/bson/ext/bson.o] Error 1
make: Leaving directory '/server/web/main/node_modules/mongo-sync/node_modules/bson/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /server/web/main/node_modules/mongo-sync/node_modules/bson
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by mbroadst** [comment]
@neoneosa looks like the module potentially needs to be updated to a newer version of NAN, either way this is a `bson-ext` issue, not one with `js-bson`.
