### ISSUE TITLE
Example from readme not working

### ISSUE THREAD

**Issue by mnn** [mongodb/js-bson#278]
I did:

```sh
npm i -S bson
```

I copied Node example:

```js
const BSON = require('bson');
const Long = BSON.Long;

const doc = { long: Long.fromNumber(100) };

// Serialize a document
const data = BSON.serialize(doc);
console.log('data:', data);

// Deserialize the resulting Buffer
const doc_2 = BSON.deserialize(data);
console.log('doc_2:', doc_2);
```

executed `node src/index.js` and it crashed:

```
index.js:7
const data = BSON.serialize(doc);
                  ^

TypeError: BSON.serialize is not a function
    at Object.<anonymous> (/xxx/index.js:7:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Package version: 3.0.2 (installed today)

**Comment by daprahamian** [comment]
Hi @mnn,

Apologies, the readme is currently for the upcoming 4.x branch which is in beta right now. You can find the readme for 3.0.2 [here](https://github.com/mongodb/js-bson/tree/v3.0.2). The only difference is that you need to make a `new BSON();` object instead of calling the methods on `BSON` directly.
