### ISSUE TITLE
Error with large data - ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by poteat** [mongodb/js-bson#335]
Unfortunately the way buffers are handled in this package causes an ERR_OUT_OF_RANGE error with very large data.  I'm guessing that at some point the buffer exists as a string, which in cases of large data exceeds the maximum string size in Node.

For any users of this library who are experiencing this error, the package "bsonfy" does not have this issue (albeit it is not native and therefore slower).

**Comment by mbroadst** [comment]
@poteat can you give a more concrete example of the problem you're running into? What does the input look like, or at least how large is it? This library uses a shared buffer to speed up parsing, but we let you [set the size of the buffer](https://github.com/mongodb/js-bson/blob/master/lib/bson.js#L36-L47) to whatever you want.

**Comment by agolin95** [comment]
Closing since we have not heard back, but please feel free to open another issue (or reopen this one) if you are still experiencing problems!

**Comment by kuworking** [comment]
In my case I'm receiving this message:

```
Error: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825794
```

The string is a long json data structure (saved in file is 50-60 Mb)

```js
//nodejs - es6
import { Long, serialize, deserialize } from 'bson'

//...

const dataz = await serialize(data) // ERROR
fs.writeFileSync('./file.json', dataz, () => {})
```

**Comment by penguinsAreFunny** [comment]
For people finding this on google:
Got the same error. Created jira-ticket https://jira.mongodb.org/projects/NODE/issues/NODE-3685

NPM MongoDB: v4.1.3
Node: v14.17.0
[MongoDB Server: 4.4.1 2008R2Plus SSL (64bit) should not be relevant though]
[See: https://github.com/mongodb/js-bson/issues/335]

I am storing multidimensiononal number arrays and some strings as a big object.
Not sure if this a NodeJS- or a MongoDB-bug. (Or maybe my bug???) 
On storing big objects to a DB I get the following error and stack trace:


ERROR: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825798
at validateOffset (buffer.js:104:3)
at Buffer.write (buffer.js:1055:5)
at serializeNumber (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:63:18)
at serializeInto (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:711:17)
at serializeObject (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
at serializeInto (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:729:17)
at serializeObject (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
at serializeInto (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:947:17)
at serializeObject (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:347:18)
at serializeInto (C:\Users\Robert\Desktop\workdir\ma-implementation-3\implementation\node_modules\mongodb\node_modules\bson\lib\bson\parser\serializer.js:729:17) {
code: 'ERR_OUT_OF_RANGE'
